### ISSUE TITLE
suggestion for the lora PA.

### ISSUE THREAD

**Issue by wangpengli** [faydr/QMesh#1]
we used a PA which include the tx/rx switch from Skyworks , model is SKY65366, it's have 30dBm output gain.

**Comment by faydr** [comment]
Thanks for the suggestion. Right now, I'm using the EByte E22 modules, which have a 30dBm PA and a 1-2dB NF LNA in them.

This is what the inside of the E22 900M30 looked like without the shield can FYI:
![image](https://user-images.githubusercontent.com/33201069/71768016-9e781800-2ecf-11ea-9d92-2d0c7f4ba9db.png)

On a similar note, do you have any experience with LoRa designs in the 220MHz-230MHz? That's an appealing band for LoRa use in the US, as the 1.25m band is less utilized than the 70cm band and it's the lowest frequency that we're allowed to use spread spectrum with.

**Comment by wangpengli** [comment]
I use SX1278 with 470MHZ , it's good . I make a radio prototype for test ,
use some protocol like you QMesh.

faydr <notifications@github.com> 于2020年1月4日周六 下午11:56写道：

**Comment by wangpengli** [comment]
[image: image.png]
[image: image.png]
[image: image.png]
For your reference.

faydr <notifications@github.com> 于2020年1月4日周六 下午11:56写道：

**Comment by wangpengli** [comment]
seems the picture can not upload by mail, so would you give me your private email?

**Comment by faydr** [comment]
daniel.fay@gmail.com

Sorry for the delay in getting back to you, I got really sick in the last two weeks.

**Comment by faydr** [comment]
I'm going to close this issue. I'll keep in mind this part for future developments.
